### ISSUE TITLE
首次访问Status显示：(failed) net::ERR_HTTP2_PROTOCOL_ERROR, 页面也没有正常展示

### ISSUE THREAD

**Issue by dean-shanghai** [toolgood/StaticPage#2]
首次访问Status显示：(failed) net::ERR_HTTP2_PROTOCOL_ERROR, 页面也没有正常展示，如图：

![首次访问异常](https://github.com/user-attachments/assets/d077acba-ce3c-4aa5-a262-95e7d4fab372)

**Comment by toolgood** [comment]
ERR_HTTP2_PROTOCOL_ERROR 是一个Chrome浏览器中的错误，表明浏览器在使用HTTP/2协议时遇到了协议违规的情况。这可能是由于服务器发送了不符合HTTP/2标准的响应导致的。

**Comment by toolgood** [comment]
我更新到.net 8，没有重现这个问题

**Comment by dean-shanghai** [comment]
报错情况只在首次访问页面时出现（首次访问页面：html文件夹中还没有生成该页面的.html/.gzip/.br等缓存文件）。

报错信息：System.InvalidOperationException: Headers are read-only, response has already started.
`fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Headers are read-only, response has already started.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
         at Microsoft.AspNetCore.Mvc.HtmlStaticFileAttribute.OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next) in C:\...\Attributes\HtmlStaticFileAttribute.cs:line`

报错的位置是这一句：`context.HttpContext.Response.Headers["Cache-Control"] = "max-age=" + (CurrPageExpireMinutes ?? ExpireMinutes) * 60;`
`            else
            {
                await base.OnResultExecutionAsync(context, next);
                var old = response.Body.Position;
                if (response.StatusCode == 200)
                {
                    await SaveHtmlResult(response.Body, filePath);
                }
                response.Body.Position = old;
            }
            //更新时，不添加页面缓存
            if (IsUpdateOutputFile(context) == false)
            {
                var fi = new FileInfo(filePath);
                var etag = fi.LastWriteTimeUtc.Ticks.ToString();
                **context.HttpContext.Response.Headers["Cache-Control"] = "max-age=" + (CurrPageExpireMinutes ?? ExpireMinutes) * 60;**
                context.HttpContext.Response.Headers["Etag"] = etag;
                context.HttpContext.Response.Headers["Date"] = DateTime.Now.ToString("r");
                context.HttpContext.Response.Headers["Expires"] = DateTime.Now.AddMinutes(CurrPageExpireMinutes ?? ExpireMinutes).ToString("r");
            }
        }


        /// <summary>
        /// 保存Html结束为静态文件
        /// </summary>
        /// <param name="stream"></param>
        /// <param name="filePath"></param>
        /// <returns></returns>
        private async Task SaveHtmlResult(Stream stream, string filePath)`

**Comment by toolgood** [comment]
修改好了，添加了一个判断 
``` cs
                if (context.HttpContext.Response.Headers.IsReadOnly == false) {
                    var fi = new FileInfo(filePath);
                    var etag = fi.LastWriteTimeUtc.Ticks.ToString();
                    context.HttpContext.Response.Headers["Cache-Control"] = "max-age=" + (CurrPageExpireMinutes ?? ExpireMinutes) * 60;
                    context.HttpContext.Response.Headers["Etag"] = etag;
                    context.HttpContext.Response.Headers["Date"] = DateTime.Now.ToString("r");
                    context.HttpContext.Response.Headers["Expires"] = DateTime.Now.AddMinutes(CurrPageExpireMinutes ?? ExpireMinutes).ToString("r");
                }
```
